const actionTypes = {
  REQUEST_TOPICS: "LOAD_TOPICS",
  REQUEST_TOPICS_SUCCEDED: "REQUEST_TOPICS_SUCCEDED",
  REQUEST_TOPICS_FAILED: "REQUEST_TOPICS_FAILED",
  SELECT_TOPIC: "SELECT_TOPIC",
  REQUEST_LINKS_SUCCEDED: "REQUEST_LINKS_SUCCEDED",
  REQUEST_LINKS_FAILED: "REQUEST_LINKS_FAILED",
  REQUEST_LINKS: "REQUEST_LINKS",
  TOOGLE_DRAWER: "TOOGLE_DRAWER",
  LOGIN: "LOGIN",
  CANCEL_LOGIN: "CANCEL_LOGIN",
  START_ADD: "START_ADD",
  CANCEL_ADD: "CANCEL_ADD",
  ADD_LINK: "ADD_LINK",
  ADD_LINK_SUCCESS: "ADD_LINK_SUCCESS",
  ADD_LINK_FAILED: "ADD_LINK_FAILED"
};

export default actionTypes;
