const actionTypes = {
  REQUEST_TOPICS: "LOAD_TOPICS",
  REQUEST_TOPICS_SUCCEDED: "REQUEST_TOPICS_SUCCEDED",
  REQUEST_TOPICS_FAILED: "REQUEST_TOPICS_FAILED",
  SELECT_TOPIC: "SELECT_TOPIC",
  REQUEST_LINKS_SUCCEDED: "REQUEST_LINKS_SUCCEDED",
  REQUEST_LINKS_FAILED: "REQUEST_LINKS_FAILED"
};

export default actionTypes;
